import type { CreateVehicleTransactionData } from '@zcorp/shared-typing-wheelz';

export const baseCreateTransactionData: CreateVehicleTransactionData = {
  vin: '',
  userId: '',
  features: {
    brand: '',
    model: '',
    cvPower: 0,
    color: '',
    tvv: '',
    cnitNumber: '',
    receptionType: '',
    technicallyAdmissiblePTAC: 0,
    ptac: 0,
    ptra: 0,
    ptService: 0,
    ptav: 0,
    category: '',
    gender: '',
    ceBody: '',
    nationalBody: '',
    receptionNumber: '',
    displacement: 0,
    netPower: 0,
    energy: '',
    seatingNumber: 0,
    standingPlacesNumber: 0,
    sonorousPowerLevel: 0,
    engineSpeed: 0,
    co2Emission: 0,
    pollutionCode: '',
    powerMassRatio: 0,
  },
  infos: {
    holderCount: 0,
    firstRegistrationInFranceDate: '',
    firstSivRegistrationDate: '',
    licensePlate: '',
    sivConversionDate: '',
  },
  history: [],
  technicalControls: [],
  sinisterInfos: {
    count: 0,
    lastResolutionDate: '',
    lastSinisterDate: '',
  },
};
